// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/crowdigit/ymm/db (interfaces: Database)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	db "github.com/crowdigit/ymm/db"
	gomock "github.com/golang/mock/gomock"
	bun "github.com/uptrace/bun"
)

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// BunDB mocks base method.
func (m *MockDatabase) BunDB() *bun.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BunDB")
	ret0, _ := ret[0].(*bun.DB)
	return ret0
}

// BunDB indicates an expected call of BunDB.
func (mr *MockDatabaseMockRecorder) BunDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BunDB", reflect.TypeOf((*MockDatabase)(nil).BunDB))
}

// InsertUploader mocks base method.
func (m *MockDatabase) InsertUploader(arg0 *bun.InsertQuery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUploader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertUploader indicates an expected call of InsertUploader.
func (mr *MockDatabaseMockRecorder) InsertUploader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUploader", reflect.TypeOf((*MockDatabase)(nil).InsertUploader), arg0)
}

// SelectUploader mocks base method.
func (m *MockDatabase) SelectUploader(arg0 *bun.SelectQuery) ([]db.Uploader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectUploader", arg0)
	ret0, _ := ret[0].([]db.Uploader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectUploader indicates an expected call of SelectUploader.
func (mr *MockDatabaseMockRecorder) SelectUploader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectUploader", reflect.TypeOf((*MockDatabase)(nil).SelectUploader), arg0)
}

// StoreMetadata mocks base method.
func (m *MockDatabase) StoreMetadata(arg0 string, arg1 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreMetadata", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreMetadata indicates an expected call of StoreMetadata.
func (mr *MockDatabaseMockRecorder) StoreMetadata(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreMetadata", reflect.TypeOf((*MockDatabase)(nil).StoreMetadata), arg0, arg1)
}
